import { index } from "@/actions/postsApi";
import Card from "@/components/Card";
import Head from "next/head";
import React, { Fragment } from "react";
import { Col, Container, Row } from "react-bootstrap";

const Posts = ({ posts }) => {
	// display posts
  const generatePosts = () => {
    return posts?.map((post) => {
      return (
        <Col sm={12} md={6} lg={4}>
          <Card post={post} />
        </Col>
      );
    });
  };

  return (
    <Fragment>
      <Head>
        <title>Astrophy posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container style={{ paddingTop: 150, paddingBottom: 100 }}>
        <Row>{generatePosts()}</Row>
      </Container>
    </Fragment>
  );
};

export const getServerSideProps = async (ctx) => {
  const res = await index();
  return {
    props: {
      posts: res.data,
    },
  };
};

export default Posts;
