import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Fragment } from "react";
import Header from "@/components/Header";
import { index } from "@/actions/postsApi";
import Card from "@/components/Card";
import { Col, Container, Row } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ posts }) {
  const generatePosts = () => {
    return posts?.map((post) => {
      return (
        <Col key={post._id} sm={12} md={6} lg={4}>
          <Card post={post} />
        </Col>
      );
    });
  };
  return (
    <Fragment>
      <Head>
        <title>Astrophy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container style={{marginTop: 100, paddingBottom: 100}}>
        <Row>{generatePosts()}</Row>
      </Container>
    </Fragment>
  );
}

export const getServerSideProps = async (ctx) => {
  const res = await index();
  return {
    props: {
      posts: res.data,
    },
  };
};
