import React, { Fragment, useState } from "react";
import styles from "@/styles/PostShow.module.css";
import { remove, show } from "@/actions/postsApi";
import { url } from "@/actions/baseUrl";
import { Button } from "react-bootstrap";
import { useRouter } from "next/router";
import Head from "next/head";
import ModalCom from "@/components/ModalCom";

const PostShow = ({ post }) => {
  const router = useRouter();
  const [open, setOpen] = useState(false);

  const handleRemove = () => {
    remove(post._id).then((res) => {
      router.push("/posts");
    });
  };

  const handleClose = () => {
    setOpen(false);
  };
  return (
    <Fragment>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.imageContainer}>
          <img
            crossOrigin="anonymous"
            alt={post.title}
            className={styles.image}
            src={`${url}/posts/${post._id}/image`}
          />
        </div>
        <div className={`d-flex gap-4 mt-4`}>
          <h3 className={styles.title}>{post.title}</h3>
          <Button onClick={() => router.push(`/posts/${post._id}/edit`)}>
            Edit
          </Button>
          <Button onClick={() => setOpen(true)} variant="secondary">
            Remove
          </Button>
        </div>
        <div
          className={styles.title}
          dangerouslySetInnerHTML={{ __html: post.body }}
        ></div>
      </div>
      <ModalCom
        open={open}
        title={`Remove ${post.title}`}
        text={`Are you sure to remove ${post.title}?`}
        approve={handleRemove}
        refuse={handleClose}
      />
    </Fragment>
  );
};

export const getServerSideProps = async (ctx) => {
  const res = await show(ctx.query.id);
  return {
    props: {
      post: res.data,
    },
  };
};

export default PostShow;
